---
# tasks file for local_system

- name: Include vars
  ansible.builtin.import_tasks: include_vars.yml

- name: Prepare the system
  ansible.builtin.import_tasks: prepare.yml
  become: true

- name: "Include tasks based on {{ ansible_os_family | lower }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Rewrite KDE neon to Ubuntu
  ansible.builtin.set_fact:
    ansible_distribution_corrected: Ubuntu
  when: ansible_distribution == "KDE neon"

- name: "Install extra software based on the {{ ansible_distribution_corrected | default(ansible_distribution) | lower }}"
  ansible.builtin.include_tasks: "extra_software/{{ ansible_distribution_corrected | default(ansible_distribution) | lower }}.yml"

- name: Install useful shell helpers
  ansible.builtin.import_tasks: "shell_helpers/shell_helpers.yml"

- name: Install fonts
  ansible.builtin.import_tasks: "fonts/fonts.yml"

- name: Place vscode config
  ansible.builtin.import_tasks: "vscode.yml"

- name: Install rambox from repo
  ansible.builtin.import_tasks: "rambox.yml"
