---

- name: Install sudo package
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create sudo group
  ansible.builtin.group:
    name: "{{ item }}"
    system: yes
    state: present
  loop:
    - sudo
    - sudo-password

- name: Install new sudoers after validation
  ansible.builtin.copy:
    src: sudoers
    dest: /etc/sudoers
    validate: 'visudo -cf %s'
    mode: "0440"
  tags:
    - sudoers
