---

- name: Install Fira Code from package manager when
  block:

  - name: Install fonts-firacode
    ansible.builtin.package:
      name: fonts-firacode
      state: present
    when: >
      ((ansible_distribution == 'Ubuntu' or ansible_distribution_corrected == "Ubuntu") and ansible_distribution_version is version('17.10','>='))
      or (ansible_distribution == 'Debian' and ansible_distribution_major_version is version('9','>='))

  when:
    - local_system_firacode == 'package'

- name: Install Fira Code from git
  block:

    - name: Ensure presence of fonts-dir
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0775"
      loop:
        - ~/.local/share/fonts/FiraCode
        - /tmp/FiraCode

    - name: Download FiraCode Font Archive and extract
      ansible.builtin.unarchive:
        src: "https://github.com/tonsky/FiraCode/releases/download/{{ local_system_firacode }}/Fira_Code_v{{ local_system_firacode }}.zip"
        dest: /tmp/FiraCode
        remote_src: true

    - name: Place FiraCode in user font folder
      ansible.posix.synchronize:
        src: /tmp/FiraCode/ttf/
        dest: "{{ ansible_env.HOME }}/.local/share/fonts/FiraCode"
        checksum: true
        archive: false
        recursive: true
      delegate_to: "{{ inventory_hostname }}"
      notify: font-cache

  when: local_system_firacode != 'package'
