---

- name: Ensure presence of fonts-dir
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0775"
  loop:
    - ~/.local/share/fonts/iosevka
    - /tmp/iosevka

- name: Download Iosevka SS05 (Fira Style) Package
  ansible.builtin.unarchive:
    src: "https://github.com/be5invis/Iosevka/releases/download/{{ local_system_iosevka }}/ttf-iosevka-ss05-{{ local_system_iosevka[1:] }}.zip"
    dest: /tmp/iosevka
    remote_src: yes
    mode: "0755"

- name: Copy over Iosevka TTFs
  ansible.builtin.copy:
    src: /tmp/iosevka/
    dest: ~/.local/share/fonts/iosevka
    remote_src: yes
    mode: "0755"
  notify: font-cache
