---

- name: Ensure presence of fonts-dir
  ansible.builtin.file:
    path: ~/.local/share/fonts/NerdFonts
    state: directory
    mode: "0755"

- name: Clone nerdfonts
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: ~/projects/nerd-fonts
    version: master
    depth: "1"
    force: yes
  notify: nerdfont-install

- name: Make install.sh executable
  ansible.builtin.file:
    path: ~/projects/nerd-fonts/install.sh
    mode: "a+x"
