---

- name: Ensure presence of fonts-dir
  file:
    path: ~/.local/share/fonts/NerdFonts
    state: directory

- name: Clone nerdfonts
  git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    dest: ~/projects/nerd-fonts
    version: master
    depth: "1"
    force: yes
  notify: nerdfont-install

- name: Make install.sh executable
  file:
    path: ~/projects/nerd-fonts/install.sh
    mode: "a+x"
