---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: local-system
    box: ubuntu/focal64
    memory: 2048
    cpus: 2
    command: ${MOLECULE_DOCKER_COMMAND:-""}
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK_CONVERGE:-converge.yml}
  inventory:
    links:
      hosts: inventory.yml
verifier:
  name: ansible
