---

- name: Prepare hosts
  hosts: all
  become: true
  tasks:
    - name: Warmup apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: (ansible_os_family | lower) == "debian"
    - name: Create certain man directories needed for install
      ansible.builtin.file:
        path: "/usr/share/man/man{{ item }}"
        state: directory
      with_sequence: start=1 end=8
      when: (ansible_os_family | lower) == "debian"
