---

- name: Copy bash configs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/{{ item }}"
    mode: "0640"
  loop:
    - .bashrc
    - .profile
    - .aliases

- name: Symlink .aliases
  ansible.builtin.file:
    src: ~/.aliases
    dest: ~/.bash_aliases
    state: link
