---

- name: Clone prettyping
  ansible.builtin.git:
    repo: https://github.com/denilsonsa/prettyping.git
    dest: ~/projects/shell-helpers/prettyping
    version: "{{ local_system_prettyping }}"
    depth: "1"

- name: Ensure presence of dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - bash
    - iputils-ping
    - gawk

- name: Download prettyping and place globally
  become: yes
  ansible.builtin.copy:
    src: ~/projects/shell-helpers/prettyping/prettyping
    dest: /usr/local/bin/prettyping
    remote_src: yes
    mode: "0755"
    owner: root
    group: root
