---

- name: Clone tldr-sh-client
  ansible.builtin.git:
    repo: https://github.com/raylee/tldr-sh-client.git
    dest: ~/projects/shell-helpers/tldr-sh-client
    version: "{{ local_system_tldr }}"
    depth: "1"

- name: Ensure presence of dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - curl

- name: Copy tldr to /tmp
  ansible.builtin.copy:
    src: ~/projects/shell-helpers/tldr-sh-client/tldr
    dest: /tmp/tldr
    remote_src: true
    mode: "0755"

- name: Install tldr-sh-client from /tmp
  become: true
  ansible.builtin.copy:
    src: /tmp/tldr
    dest: /usr/local/bin/tldr
    remote_src: true
    mode: "0755"
    owner: root
    group: root
