---

- name: Copy .pam_environment for SSH_AUTH_SOCK
  ansible.builtin.copy:
    src: wayland-ssh-agent/.pam-environment
    dest: ~/.pam-environment
    mode: "0644"

- name: Ensure presence of ~/.config/systemd/user
  ansible.builtin.file:
    path: ~/.config/systemd/user
    state: directory
    mode: "0775"

- name: Copy ssh-agent unit to user dir
  ansible.builtin.copy:
    src: wayland-ssh-agent/ssh-agent.service
    dest: ~/.config/systemd/user/ssh-agent.service
    mode: "0664"
  register: local_system_ssh_agent

- name: Systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: local_system_ssh_agent | changed

- name: Enable and start ssh-agent.service
  ansible.builtin.systemd:
    name: ssh-agent
    state: started
    enabled: yes
    scope: user
